[package]
name = "gist"
description = "A simple Github Gist client"
version = "0.9.0"
authors = ["Arnaud Berthomier <oz@cyprio.net>"]
license = "MIT"
repository = "https://github.com/oz/gist"
readme = "README.md"

[dependencies]
getopts = "~0.2"
ureq = { version = ">=2.3", features = ["json", "charset"] }
serde = "~1.0"
serde_json = "~1.0"
serde_derive = "~1.0"
anyhow = "~1.0"
dirs-next = "2.0.0"
